Feature:site_map
  @javascript
  
Scenario: walk through the site map
  Given I am on "/"
  Then I should see "puuk.ee"
  
  When I click on the text "Kes on puuk?"
  
  Then I should see "Kes on puuk?"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  And I wait for 2 seconds
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[2]/a"
  Then I should see "Puugihammustus"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Haigused"
  Then I should see "Puukentsefaliidi viirus (TBE-viirus)"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Puukentsefaliidi viirus (TBE-viirus)"
  Then I should see "Puukentsefaliidi viirus (TBE-viirus)"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Puukborrelioos"
  Then I should see "Puukborrelioos"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Erlihhioos"
  Then I should see "Erlihhioos"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[3]/a"
  Then I should see "Kaitse ja ennetamine"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Puugi eemaldamine"
  Then I should see "Puugi eemaldamine"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Lapsed"
  Then I should see "Lapsed"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Loomad"
  Then I should see "Loomad"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[4]/a"
  Then I should see "Korduvad küsimused ja vastused"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Minu lugu"
  Then I should see "Minu lugu"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Küsi spetsialistilt"
  Then I should see "Küsi spetsialistilt"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[5]/a"
  Then I should see "Uudised"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[6]/a"
  Then I should see "Uudised"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Kirjandus"
  Then I should see "Kirjandus"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Euroopa levikukaart"
  Then I should see "Euroopa levikukaart"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Videod"
  Then I should see "Videod"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the text "Pildid"
  Then I should see "Pildid"
  When I click on the element with xpath "//*[@id='block-block-16']/div/div[2]/div/div/a[1]"
  Then I should see "Sisujuht"
  When I click on the element with xpath "//*[@id='node-281']/div/div/div[2]/div/div/ul/li[7]/a"
  Then I should see "Baxter"
  
